name: GoodWidget Spec Template
description: Define the requirements for a new GoodWidget
body:
  - type: markdown
    attributes:
      value: |
        # GoodWidget Spec Template

        define the specification for a new app, widget or UI based on GoodWidget framework

  - type: textarea
    id: description
    attributes:
      label: description
      description: |
        What new app, widget or UI component should be created based on the GoodWidget framework?
        What problem does it solve?
        How does it fit the project goals?
      placeholder: |
        What new app, widget or UI component should be created based on the GoodWidget framework?
        What problem does it solve?
        How does it fit the project goals?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Create the plan
        Update this issue description with an execution plan.

        - Map relevant files that are too be used as reference from all repos mentioned
        - import existing @GoodDollar packages
        - Map new components that should be created. Assess when a new component should be created in the new savings widget package or made part of the reusable packages/ui

        Plan specification required sections:

        - Required states, flows, and behaviors
        - Execution plan
        - acceptance criteria
        - human-reviewer checklist
