import { createTokens, createTheme } from 'tamagui'

export const tokens = createTokens({
  color: {
    primary: '#00AEFF',
    primaryDark: '#0085C5',
    primaryLight: '#66CFFF',
    secondary: '#00C3AE',
    secondaryDark: '#009A89',
    success: '#00B0AD',
    warning: '#F5A623',
    error: '#E53935',
    errorLight: '#FFCDD2',

    white: '#FFFFFF',
    black: '#000000',
    background: '#FFFFFF',
    backgroundDark: '#121212',
    surface: '#F5F7FA',
    surfaceDark: '#1E1E1E',
    text: '#333333',
    textDark: '#E0E0E0',
    textSecondary: '#71727A',
    textSecondaryDark: '#A0A0A0',
    border: '#E0E0E0',
    borderDark: '#333333',
    overlay: 'rgba(0,0,0,0.5)',
    transparent: 'transparent',
  },
  size: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    11: 48,
    12: 56,
    13: 64,
    14: 80,
    true: 40,
  },
  space: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    7: 28,
    8: 32,
    9: 36,
    10: 40,
    true: 16,
  },
  radius: {
    0: 0,
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    true: 8,
  },
  zIndex: {
    0: 0,
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
  },
})

export const lightTheme = createTheme({
  background: tokens.color.background,
  backgroundHover: tokens.color.surface,
  backgroundPress: tokens.color.border,
  backgroundFocus: tokens.color.surface,
  backgroundTransparent: tokens.color.transparent,

  color: tokens.color.text,
  colorHover: tokens.color.text,
  colorPress: tokens.color.textSecondary,
  colorFocus: tokens.color.text,
  colorTransparent: tokens.color.transparent,

  borderColor: tokens.color.border,
  borderColorHover: tokens.color.primary,
  borderColorPress: tokens.color.primaryDark,
  borderColorFocus: tokens.color.primary,

  placeholderColor: tokens.color.textSecondary,

  shadowColor: 'rgba(0,0,0,0.1)',
  shadowColorHover: 'rgba(0,0,0,0.15)',
  shadowColorPress: 'rgba(0,0,0,0.05)',
  shadowColorFocus: 'rgba(0,0,0,0.15)',
})

export const darkTheme = createTheme({
  background: tokens.color.backgroundDark,
  backgroundHover: tokens.color.surfaceDark,
  backgroundPress: tokens.color.borderDark,
  backgroundFocus: tokens.color.surfaceDark,
  backgroundTransparent: tokens.color.transparent,

  color: tokens.color.textDark,
  colorHover: tokens.color.textDark,
  colorPress: tokens.color.textSecondaryDark,
  colorFocus: tokens.color.textDark,
  colorTransparent: tokens.color.transparent,

  borderColor: tokens.color.borderDark,
  borderColorHover: tokens.color.primary,
  borderColorPress: tokens.color.primaryDark,
  borderColorFocus: tokens.color.primary,

  placeholderColor: tokens.color.textSecondaryDark,

  shadowColor: 'rgba(0,0,0,0.3)',
  shadowColorHover: 'rgba(0,0,0,0.4)',
  shadowColorPress: 'rgba(0,0,0,0.2)',
  shadowColorFocus: 'rgba(0,0,0,0.4)',
})

export const lightComponentThemes = {
  light_Button: createTheme({
    background: tokens.color.primary,
    backgroundHover: tokens.color.primaryDark,
    backgroundPress: tokens.color.primaryDark,
    backgroundFocus: tokens.color.primaryDark,
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.white,
    colorHover: tokens.color.white,
    colorPress: tokens.color.white,
    colorFocus: tokens.color.white,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.transparent,
    borderColorHover: tokens.color.transparent,
    borderColorPress: tokens.color.transparent,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.white,
    shadowColor: 'rgba(0,174,255,0.3)',
    shadowColorHover: 'rgba(0,174,255,0.4)',
    shadowColorPress: 'rgba(0,174,255,0.2)',
    shadowColorFocus: 'rgba(0,174,255,0.4)',
  }),

  light_Card: createTheme({
    background: tokens.color.white,
    backgroundHover: tokens.color.surface,
    backgroundPress: tokens.color.surface,
    backgroundFocus: tokens.color.surface,
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.text,
    colorHover: tokens.color.text,
    colorPress: tokens.color.textSecondary,
    colorFocus: tokens.color.text,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.border,
    borderColorHover: tokens.color.border,
    borderColorPress: tokens.color.border,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.textSecondary,
    shadowColor: 'rgba(0,0,0,0.08)',
    shadowColorHover: 'rgba(0,0,0,0.12)',
    shadowColorPress: 'rgba(0,0,0,0.04)',
    shadowColorFocus: 'rgba(0,0,0,0.12)',
  }),

  light_Input: createTheme({
    background: tokens.color.white,
    backgroundHover: tokens.color.white,
    backgroundPress: tokens.color.white,
    backgroundFocus: tokens.color.white,
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.text,
    colorHover: tokens.color.text,
    colorPress: tokens.color.text,
    colorFocus: tokens.color.text,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.border,
    borderColorHover: tokens.color.primary,
    borderColorPress: tokens.color.primaryDark,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.textSecondary,
    shadowColor: 'rgba(0,0,0,0.05)',
    shadowColorHover: 'rgba(0,174,255,0.1)',
    shadowColorPress: 'rgba(0,0,0,0.05)',
    shadowColorFocus: 'rgba(0,174,255,0.15)',
  }),
}

export const darkComponentThemes = {
  dark_Button: createTheme({
    background: tokens.color.primary,
    backgroundHover: tokens.color.primaryLight,
    backgroundPress: tokens.color.primaryDark,
    backgroundFocus: tokens.color.primaryLight,
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.white,
    colorHover: tokens.color.white,
    colorPress: tokens.color.white,
    colorFocus: tokens.color.white,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.transparent,
    borderColorHover: tokens.color.transparent,
    borderColorPress: tokens.color.transparent,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.white,
    shadowColor: 'rgba(0,174,255,0.2)',
    shadowColorHover: 'rgba(0,174,255,0.3)',
    shadowColorPress: 'rgba(0,174,255,0.1)',
    shadowColorFocus: 'rgba(0,174,255,0.3)',
  }),

  dark_Card: createTheme({
    background: tokens.color.surfaceDark,
    backgroundHover: '#252525',
    backgroundPress: '#1A1A1A',
    backgroundFocus: '#252525',
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.textDark,
    colorHover: tokens.color.textDark,
    colorPress: tokens.color.textSecondaryDark,
    colorFocus: tokens.color.textDark,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.borderDark,
    borderColorHover: tokens.color.borderDark,
    borderColorPress: tokens.color.borderDark,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.textSecondaryDark,
    shadowColor: 'rgba(0,0,0,0.2)',
    shadowColorHover: 'rgba(0,0,0,0.3)',
    shadowColorPress: 'rgba(0,0,0,0.1)',
    shadowColorFocus: 'rgba(0,0,0,0.3)',
  }),

  dark_Input: createTheme({
    background: tokens.color.surfaceDark,
    backgroundHover: tokens.color.surfaceDark,
    backgroundPress: tokens.color.surfaceDark,
    backgroundFocus: tokens.color.surfaceDark,
    backgroundTransparent: tokens.color.transparent,
    color: tokens.color.textDark,
    colorHover: tokens.color.textDark,
    colorPress: tokens.color.textDark,
    colorFocus: tokens.color.textDark,
    colorTransparent: tokens.color.transparent,
    borderColor: tokens.color.borderDark,
    borderColorHover: tokens.color.primary,
    borderColorPress: tokens.color.primaryDark,
    borderColorFocus: tokens.color.primary,
    placeholderColor: tokens.color.textSecondaryDark,
    shadowColor: 'rgba(0,0,0,0.1)',
    shadowColorHover: 'rgba(0,174,255,0.1)',
    shadowColorPress: 'rgba(0,0,0,0.1)',
    shadowColorFocus: 'rgba(0,174,255,0.15)',
  }),
}
