export { createMiniAppElement } from './createMiniAppElement'
export { injectStylesIntoShadow, updateShadowStyles, getResetCSS } from './shadowStyles'
export { readCSSOverrides, observeCSSChanges } from './cssPropertyBridge'
export { emitEvent, toKebabCase, toCamelCase, normalizePropDefs } from './bridge'
export type { PropDefinitions, PropType, PropDefinition } from './bridge'
