import React, { useState } from 'react'
import {
  Button,
  ButtonText,
  Card,
  Heading,
  Icon,
  Spinner,
  Text,
  XStack,
  YStack,
} from '@goodwidget/ui'
import { truncateAddress, compactButtonProps } from '../shared/styles'

interface OperatorConsentStepProps {
  buyerPubKey: string | null
  buyerPrvKey: string | null
  operatorSignature?: string | null
  operatorConsented: boolean
  operatorConsentPending?: boolean
  onSign: () => Promise<void>
  /** Signer key this wallet derives, when the browser already knows it. */
  derivedBuyerAddress?: string | null
  /** Re-derives this wallet's signer key, for a browser that no longer holds it. */
  onRestoreKey?: () => Promise<void>
  embedded?: boolean
}

function ConsentBullet({ children }: { children: React.ReactNode }) {
  return (
    <XStack gap="$2" alignItems="flex-start">
      <Text fontSize="$2" secondary lineHeight="$3">
        •
      </Text>
      <Text fontSize="$2" secondary lineHeight="$3" flex={1}>
        {children}
      </Text>
    </XStack>
  )
}

export function OperatorConsentStep({
  buyerPubKey,
  buyerPrvKey,
  operatorSignature = null,
  operatorConsented,
  operatorConsentPending = false,
  onSign,
  derivedBuyerAddress = null,
  onRestoreKey,
  embedded = false,
}: OperatorConsentStepProps) {
  const [restorePending, setRestorePending] = useState(false)
  const canSign = Boolean(buyerPubKey && (buyerPrvKey || operatorSignature))
  const isBusy = operatorConsentPending

  // Nothing here can be signed without the signer key. Rather than show a button
  // that cannot fire, offer the action that actually unblocks it — unless this
  // wallet derives a different signer key, in which case re-deriving would switch
  // buyers behind the user's back and importing is the only honest route.
  const needsKey = Boolean(buyerPubKey) && !canSign && !operatorConsented
  const derivesDifferentKey =
    needsKey &&
    Boolean(derivedBuyerAddress) &&
    derivedBuyerAddress?.toLowerCase() !== buyerPubKey?.toLowerCase()
  const canRestoreKey = needsKey && !derivesDifferentKey && Boolean(onRestoreKey)

  const Shell = embedded ? YStack : Card

  const handleRestore = async () => {
    if (!onRestoreKey) return
    setRestorePending(true)
    try {
      await onRestoreKey()
    } finally {
      setRestorePending(false)
    }
  }

  return (
    <Shell gap="$3" {...(!embedded ? { backgroundColor: '$backgroundHover' } : {})}>
      <Heading level={5}>Authorize Wallet</Heading>
      <Text fontSize="$2" lineHeight="$3">
        GoodDollar needs this one-time authorization to fund and manage your AI credits on Base
        after you pay with G$ on Celo. It lets the GoodDollar operator move funds in your separate
        AI credits account, but never gives access to your payer wallet or G$. Granting this
        permission means trusting GoodDollar with that scoped Base role; you can revoke it later
        through the account controls.
      </Text>

      <YStack gap="$1.5">
        <ConsentBullet>
          Approval happens in your wallet — your wallet app opens a request that you accept or
          reject there, not in this widget.
        </ConsentBullet>
        <ConsentBullet>It costs no gas and moves no funds.</ConsentBullet>
        <ConsentBullet>One time only — later purchases reuse it.</ConsentBullet>
      </YStack>

      {buyerPubKey && (
        <Text fontSize="$2" lineHeight="$2">
          Buyer address:{' '}
          <Text fontFamily="$mono" fontSize="$2">
            {truncateAddress(buyerPubKey)}
          </Text>
        </Text>
      )}

      {operatorConsented ? (
        <XStack gap="$2" alignItems="center">
          <Icon name="check" size="sm" color="success" />
          <Text color="$success">Wallet authorized — ready to pay</Text>
        </XStack>
      ) : derivesDifferentKey ? (
        <Text fontSize="$2" color="$warning" lineHeight="$3">
          This signer key was not generated by the connected wallet, so it cannot be restored here.
          Import its private key from the Signer key step to authorize it.
        </Text>
      ) : canRestoreKey ? (
        <>
          <Text fontSize="$2" secondary lineHeight="$3">
            This browser does not hold your signer key. Restore it from your wallet to continue —
            the same wallet always produces the same key.
          </Text>
          <Button
            size="sm"
            {...compactButtonProps}
            onPress={() => {
              void handleRestore()
            }}
            disabled={restorePending}
          >
            {restorePending ? (
              <XStack gap="$2" alignItems="center">
                <ButtonText>Restoring…</ButtonText>
                <Spinner size="sm" />
              </XStack>
            ) : (
              <ButtonText>Restore Signer Key</ButtonText>
            )}
          </Button>
        </>
      ) : (
        <Button
          size="sm"
          {...compactButtonProps}
          onPress={() => {
            void onSign()
          }}
          disabled={!canSign || isBusy}
        >
          {isBusy ? (
            <XStack gap="$2" alignItems="center">
              <ButtonText>Submitting…</ButtonText>
              <Spinner size="sm" />
            </XStack>
          ) : (
            <ButtonText>Authorize Wallet</ButtonText>
          )}
        </Button>
      )}
    </Shell>
  )
}
