export const citizenClaimIntegration = {
  id: 'citizen-claim',
  sdk: '@goodsdks/citizen-sdk',
  inviteSdk: '@goodsdks/invite-sdk@1.0.3',
  capabilitySource: 'citizenSdkCapabilities',
  uses: [
    'whitelistStatus',
    'claimStatus',
    'claimEntitlement',
    'genericClaimEntitlement',
    'dailyStats',
    'startVerification',
    'claim',
    'invite.resolveCode',
    'invite.join',
    'invite.checkEligibilityDetails',
    'invite.collectAllBounties',
  ],
  chains: [122, 42220, 50],
  states: [
    'loading',
    'connecting',
    'not_connected',
    'not_whitelisted',
    'eligible',
    'already_claimed',
    'claiming',
    'success',
    'error',
    'invite_disconnected',
    'invite_unsupported',
    'invite_loading',
    'invite_ready',
    'invite_joining',
    'invite_collecting',
    'invite_error',
  ],
  events: ['claim-success', 'claim-error'],
} as const

export type CitizenClaimIntegration = typeof citizenClaimIntegration
